#!/bin/sh
#PBS -l select=1:ncpus=5:ngpus=1:mem=16gb
#PBS -l walltime=12:00:00
#PBS -q gpu
#PBS -P 12001577
#PBS -joe

cd $PBS_O_WORKDIR

module load cuda/10.1
nvidia-smi

module load singularity
singularity exec --nv --bind wsolevaluation-master/:/mnt MyPyTorchSandBox/ python3 /mnt/xquickruns_resnet50.py   --scoremap_root=xresearchlog/resnet50_cam --scoremap_mode cam  --DISABLE_GPU 0 --ROOT_DIR wsolevaluation-master --debug_toggles 000000 



