#!/bin/sh
#PBS -l select=1:ncpus=5
#PBS -l walltime=24:00:00
#PBS -q normal
#PBS -P 12001577
#PBS -joe

cd $PBS_O_WORKDIR

module load cuda/10.1
nvidia-smi

module load singularity
singularity exec --nv --bind wsolevaluation-master/:/mnt USandbox/ python /mnt/xquickruns_resnet50.py   --scoremap_root=xresearchlog/resnet50_gradcam_NBDT --NBDT 1  --scoremap_mode gradcam --scoremap_submode input --ROOT_DIR wsolevaluation-master --debug_toggles 000000 





