#!/bin/sh
#PBS -l select=1:ncpus=8
#PBS -l walltime=48:00:00
#PBS -q normal
#PBS -P 12001577
#PBS -joe

cd $PBS_O_WORKDIR

module load cuda/10.1
nvidia-smi

module load singularity

singularity exec --nv --bind wsolevaluation-master/:/mnt USandbox/ python /mnt/xquickruns_resnet50.py   --scoremap_root=xresearchlog/resnet50_saliency_NBDT --NBDT 1 --scoremap_mode saliency --scoremap_submode layer1 --ROOT_DIR wsolevaluation-master --debug_toggles 000000  



